### ISSUE TITLE
Help，RestrictedText  Chinese character set garbled

### ISSUE THREAD

**Issue by cuinfo** [SwissAS/jcgm-core#4]
Convert cgm to png：  cgm  has  chinese character "你好"，when debug class  RestrictedText   method mkstring ，i get garbled.

How can i solve this problem?

**Comment by philippecade** [comment]
The [Command.makeString](https://github.com/SwissAS/jcgm-core/blob/1c910fcc8815d0789e59a0818e2e0400ea2119b1/src/net/sf/jcgm/core/Command.java#L164) method has a hard coded encoding set to ISO8859-1 so the chinese characters will not correctly be decoded.

I guess this could be controlled by the CHARACTER CODING ANNOUNCER command but this is not implemented at this time.

Then a font being able to draw the characters would also need to be handled correctly, the specification gives some details at 6.3.4 Fonts and character sets.

Feel free to issue pull request for this.

**Comment by cuinfo** [comment]
> The [Command.makeString](https://github.com/SwissAS/jcgm-core/blob/1c910fcc8815d0789e59a0818e2e0400ea2119b1/src/net/sf/jcgm/core/Command.java#L164) method has a hard coded encoding set to ISO8859-1 so the chinese characters will not correctly be decoded.
> 
> I guess this could be controlled by the CHARACTER CODING ANNOUNCER command but this is not implemented at this time.
> 
> Then a font being able to draw the characters would also need to be handled correctly, the specification gives some details at 6.3.4 Fonts and character sets.
> 
> Feel free to issue pull request for this.

Thanks!

CHARACTER CODING ANNOUNCER command   always  BASIC8BIT。
Debug catch the chinese characters （“你好”） hexadecimal code is 0x4f60, 0x597d； 
It's two octets,It is correct when using unicode or utf-16 encoding instead of ISO8859-1.

View documentation  at 6.3 section：
  Each character is stored in 1 or more consecutive octets, depending upon the coding of the particular character set.
 
 CharacterSet：
 0 94-character G-set
1 96-character G-set
2 94-character multibyte G-set
3 96-character multibyte G-set
4 complete code



Test：
1、contain the chinese characters file 1.cgm
2、not contain the chinese characters file 2.cgm
then debug class CharacterSetList 、AlternateCharacterSetIndex，CharacterSetIndex
 CHARSETINDEX index  ;
 ALTCHARSETINDEX  index  ;

Result：
  1.cgm always  CHARSETINDEX 1 ，then ALTCHARSETINDEX 2
  2.cgm always  CHARSETINDEX 1 ，then ALTCHARSETINDEX 2，ALTCHARSETINDEX 3 ，ALTCHARSETINDEX 4

My Idea： 
I thought that when index 2/3 is used, multi-byte decoding is required, but the decoding result is wrong.

The test found that the accuracy of the two files VDCRealPrecision is different.

Any suggestions to distinguish encoding?

**Comment by Rossi1337** [comment]
Worth reading:
http://www.cgmopen.org/webcgm/WebCGM-CGM.html
It seems only WebCGM supports unicode charsets other than the standard ISO 8859-1.

For WebCGM there seems to be additional infos here:
https://www.w3.org/TR/2019/SPSD-WebCGM20-20191205/WebCGM20-Profile.html
Search for CHARACTER SET LIST or  7.3.14 on that page. May give you some more hints how to distinguish between UTF8 and UTF16. 

We implement in CharacterCodingAnnouncer only 0 - 3 and have a default to 0. 
I assume in the file the 4 is written (haven't checked that)

**Comment by cuinfo** [comment]
> Worth reading:
> http://www.cgmopen.org/webcgm/WebCGM-CGM.html
> It seems only WebCGM supports unicode charsets other than the standard ISO 8859-1.
> 
> For WebCGM there seems to be additional infos here:
> https://www.w3.org/TR/2019/SPSD-WebCGM20-20191205/WebCGM20-Profile.html
> Search for CHARACTER SET LIST or 7.3.14 on that page. May give you some more hints how to distinguish between UTF8 and UTF16.
> 
> We implement in CharacterCodingAnnouncer only 0 - 3 and have a default to 0.
> I assume in the file the 4 is written (haven't checked that)
Thanks.

Worth reading,   The CGM  bin formart by WebCgm.
